// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAvtxU3aoo6HrE69ueQ1c8oLeuVIUKALs',
    appId: '1:706404102505:web:6f521dc3b0c3bdfa2d0df8',
    messagingSenderId: '706404102505',
    projectId: 'agri-lens',
    authDomain: 'agri-lens.firebaseapp.com',
    storageBucket: 'agri-lens.firebasestorage.app',
    measurementId: 'G-2M0ZF7B0NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6iUxJudOQJVdzPR1TZWpknd2afafbIQY',
    appId: '1:706404102505:android:6c17163f7f1135822d0df8',
    messagingSenderId: '706404102505',
    projectId: 'agri-lens',
    storageBucket: 'agri-lens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRI6ub2fNjv3Q-X_Z8XjuubbhZ4CPiQeg',
    appId: '1:706404102505:ios:1a39b4fd901583362d0df8',
    messagingSenderId: '706404102505',
    projectId: 'agri-lens',
    storageBucket: 'agri-lens.firebasestorage.app',
    iosBundleId: 'com.agri.lens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRI6ub2fNjv3Q-X_Z8XjuubbhZ4CPiQeg',
    appId: '1:706404102505:ios:b2027580b83945b82d0df8',
    messagingSenderId: '706404102505',
    projectId: 'agri-lens',
    storageBucket: 'agri-lens.firebasestorage.app',
    iosBundleId: 'com.example.argiLensApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAvtxU3aoo6HrE69ueQ1c8oLeuVIUKALs',
    appId: '1:706404102505:web:89528dd5fd7fcd722d0df8',
    messagingSenderId: '706404102505',
    projectId: 'agri-lens',
    authDomain: 'agri-lens.firebaseapp.com',
    storageBucket: 'agri-lens.firebasestorage.app',
    measurementId: 'G-TJX4FV8BP5',
  );
}
