name: agre_lens_app
description: "Agre Lens"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  intl: ^0.20.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  buildcondition: ^0.0.4
  dio: ^5.8.0+1
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  change_app_package_name: ^1.4.0
  flutter_datetime_picker_plus: ^2.1.0
  equatable: ^2.0.7
  fl_chart: ^0.70.2
  searchable_listview: ^2.16.0
  string_similarity: ^2.0.0
  syncfusion_flutter_datepicker: ^28.2.12
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.6
  firebase_database: ^11.3.5
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  http: ^1.3.0
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo App.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/Logo App foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
